name: Release

defaults:
  run:
    shell: bash

on:
  workflow_dispatch

jobs:
  release_java:
    name: Release Java module
    timeout-minutes: 20
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: [ 8 ]
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Setup Java SDK ${{ matrix.java-version }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java-version }}
      - name: Cache local Maven repository
        uses: actions/cache@v2
        env:
          cache-name: cache-maven-packages
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ env.cache-name }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Import GPG signing key
        run: echo ${{ secrets.JARVIZ_GPG_PRIVATE_KEY }} | base64 --decode | gpg --import --batch --no-tty --yes
      - name: Run release script for Java
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GPG_KEY_NAME: ${{ secrets.JARVIZ_GPG_KEY_NAME }}
          GPG_PASSPHRASE: ${{ secrets.JARVIZ_GPG_PASSPHRASE }}
        run: |
          export GPG_TTY=$(tty)
          echo "Releasing jarviz-lib for $GITHUB_REF"
          mvn package
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist-without-markdown
          path: |
            target/**/*.jar
